package.json

See https://github.com/Microsoft/TypeScript/issues/4565

Fix #21 by upgrading gulp-typescript

---

src/views/TerminalLayout.ts
views/main.js

Once I upgrade gulp as per #22, I noticed an import failure. This fixes that problem and makes the app actually work on my machine.
Thanks for the awesome project.

Removed aboslute path import and unnecesarry circular import

---

package.json

Based on #51 conversation I've remove `node_modules/.bin` from package.json, have run affected scripts and seem like everything work fine

Removed node_modules/.bin path

---

CONTRIBUTING.md

- Fix steps
- Add additional check to prevent dublicates

Bug reporting update

---

CONTRIBUTING.md

@G07cha, please review. Answer "Approved." or something, if you agree with the changes.

Correct grammar in CONTRIBUTING.md

---

README.md
package.json
src/Aliases.ts
src/Invocation.ts

* Use pty.js instead of child_pty.
* Simplify the build command.

Use pty.js instead of child_pty.

---

.editorconfig

Fixes #99 
Forces indent style, size, charset and whitespace options

Fixes #99 Added .editorconfig and basic style settings

---

src/CommandExecutor.ts
src/Invocation.ts

Extract handling of different types of executions into separate classes to avoid repetition.

Execution strategy

---

stylesheets/colors.scss
stylesheets/main.scss

Added a custom selection colour to match the asthetics of the application.

Added selection colour

---

README.md

Almost not worth it, but you know, why not.  I tested a quick copy paste of the updated command and I think it's comfy in two universes now.

tiny optimization to make the ol' git clone and cd work for bash and zsh

---

src/plugins/Show.tsx
src/shell/Command.ts
src/views/3_JobComponent.tsx

Currently there is no padding around the images which means that they are pressed up against each other. Also it seems like images don't get shrank either.

Added show command which can display images inline in the terminal

---

CONTRIBUTING.md

Fixes invalid git pull switch `-u`
Fixes missing npm script `package`
Fixes #592

Updates contributing file

---

src/plugins/autocompletion_providers/Ls.ts

I'm experimenting with generating autocomplete from man pages. This is a potential output. The content is from the man pages, IDK if using it like this jives with your license or not.

Autocomplete for ls

---

src/plugins/autocompletion_providers/Mkdir.ts

My noobishness at TypeScript is showing through here, I've used a very inelegant way of removing `undefined`s from an array. I would appreciate suggestions for how to improve that.
Thank you for adding me as a Collaborator! Would you like me to merge my own PRs? Merge other people's PRs? Anything else?

Fix mkdir autocomplete

---

src/views/1_ApplicationComponent.tsx
src/views/4_PromptComponent.tsx
src/views/Main.tsx
src/views/UserEventsHander.ts
test/e2e.js

Fixes https://github.com/shockone/black-screen/issues/643
@drew-gross please review as you modified this code before.

Move paste handling to handleUserEvent.

---

src/views/css/main.ts

Small details make the difference

Better tabs design (auto width)

---

src/Autocompletion.ts
src/Interfaces.ts
src/PluginManager.ts
src/plugins/autocompletion_providers/Cat.ts
src/plugins/autocompletion_providers/Cd.ts
src/plugins/autocompletion_providers/Git.ts
src/plugins/autocompletion_providers/Grep.ts
src/plugins/autocompletion_providers/Ln.ts
src/plugins/autocompletion_providers/Ls.ts
src/plugins/autocompletion_providers/Mkdir.ts
src/plugins/autocompletion_providers/Mv.ts
src/plugins/autocompletion_providers/NPM.ts
src/plugins/autocompletion_providers/Rails.ts
src/plugins/autocompletion_providers/Rm.ts
src/plugins/autocompletion_providers/Top.ts
src/plugins/autocompletion_providers/Vagrant.ts
src/plugins/autocompletion_utils/Combine.ts
src/plugins/autocompletion_utils/Common.ts
src/shell/Parser.ts
src/utils/ManPageParsingUtils.ts
src/utils/ManPages.ts
src/views/4_PromptComponent.tsx
src/views/AutocompleteComponent.tsx
test/utils/ManPages_spec.ts

I also had to move some code around due to some weird module loading behaviour I was seeing.

Man page autocomplete tests

---

src/shell/Scanner.ts
test/shell/scanner_spec.ts

Fix scanner for unicode characters

---

src/plugins/autocompletion_providers/Df.ts
src/plugins/autocompletion_providers/Locate.ts
src/shell/CommandExecutor.ts
src/shell/Environment.ts
src/utils/ManPageParsingUtils.ts
src/utils/ManPages.ts
test/environment_spec.ts
test/utils/ManPages_spec.ts

This allows autocomplete for df and location, although it doesn't correctly detect that -l needs an argument.

Autocomplete options that have varying indentation

---

src/plugins/autocompletion_providers/Brew.ts

I was familiarizing myself with the code and I thought I'd write an autocomplete plugin while I'm at it. Let me know if it needs any changes.

Add autocomplete for brew

---

package.json
src/PTY.ts
src/plugins/ManPage.tsx
src/references.d.ts
src/shell/Prompt.ts
typings/uuid.d.ts

Format man pages in HTML. This is based on some other unrelated commits, so it can't be merged as is, but people might want to discuss based on the screenshot and so-on.

Man page html decorator

---

src/plugins/RVM.ts

Prevent RVM observer from logging an error if you don't have RVM installed.

Fix RVM error

---

src/plugins/GitWatcher.ts
src/views/StatusBarComponent.tsx
src/views/css/main.ts
typings/Interfaces.d.ts

Extends with push and pull counters for git folder.
Wished in this issue: #716

extended git status bar with pull and push counter

---

package.json
src/plugins/Ls.tsx
src/references.d.ts
src/views/index.html
test/e2e.js
typings/dirStat.d.ts

This is a decorator for LS that essentially turns the text of each item into a link that opens the item in your default editor.
I wanted to get some feedback on what important features people might want in this.

[wip] LS decorator

---

.travis.yml

Another attempt to fix the build issues on Travis.

Update npm version

---

src/plugins/GitWatcher.ts
src/views/StatusBarComponent.tsx
src/views/css/main.ts
typings/Interfaces.d.ts

- status bar will show file change status
- fix a bug all git directory treated as dirty
The implementation of issue #715.

Implemented Issue 715's function

---

src/plugins/GitGrep.tsx

WIP. I plan to make the text be appropriately colored as well.

Add GitGrep plugin that makes the filename a link

---

src/plugins/GitBranch.tsx
src/plugins/GitStatus.tsx
src/plugins/autocompletion_providers/Git.ts
src/plugins/autocompletion_utils/Button.tsx
src/utils/Git.ts

Git branch plugin

---

src/main/Main.ts

Quit program when all windows close

---

src/views/StatusBarComponent.tsx
src/views/css/main.ts

Use ellipsis instead of breaking line when branch name and pwd don't fit in status bar

---

package.json
src/ANSIParser.ts
src/Char.ts
src/PTY.ts
src/ScreenBuffer.ts
src/plugins/GitStatus.tsx
src/shell/Parser.ts
src/utils/Common.ts
src/utils/Link.tsx
src/views/4_PromptComponent.tsx
src/views/AutocompleteComponent.tsx
src/views/css/main.ts
tslint.json

TS 2.1.4 has spread operator, hooray!

Update typescript, other deps, and remove Object.assign

---

src/Autocompletion.ts
src/Interfaces.ts
src/plugins/autocompletion_utils/Common.ts
src/shell/Parser.ts
src/views/4_PromptComponent.tsx
test/autocompletion_spec.ts

Reverts vshatskyi/black-screen#937
The PR didn't work as I'd hoped. It added a backslash in a place where it shouldn't.

Revert "Fix issue causing autocomplete arguments after a space to not work."

---

housekeeping/deploy.sh

Fix deploy script to not publish prereleases.

---

src/views/1_ApplicationComponent.tsx
src/views/Main.tsx
src/views/menu/Menu.ts

Step 2 in my attempts to refactor globals and remove flakiness.

Remove global reference "window.application"

---

src/views/1_ApplicationComponent.tsx
src/views/menu/Menu.ts
typings/Overrides.d.ts

Next step in removing global state/deflakifying.

Move tabs into React state

---

src/utils/Git.ts

Modified the "branches" function to use the "git symbolic-ref --short -q HEAD" command to determine the active Git branch.

Use "git symbolic-ref" to determine active Git branch

---

src/views/1_ApplicationComponent.tsx
src/views/3_JobComponent.tsx
src/views/Main.tsx
typings/Overrides.d.ts

Almost done removing all the globals

Remove global focusedJob

---

src/utils/PaneTree.ts
src/views/1_ApplicationComponent.tsx
src/views/2_SessionComponent.tsx
src/views/3_JobComponent.tsx
src/views/4_PromptComponent.tsx
src/views/Main.tsx
typings/Overrides.d.ts

Remove global prompt

---

src/utils/Git.ts

Improves efficiency of 'branches' function by executing two independent promise requests concurrently.
The method used to execute the two promises in parallel is based on the pattern described here:
[https://chrishiestand.github.io/2016-01-05-js-async-await/#/8](https://chrishiestand.github.io/2016-01-05-js-async-await/#/8)

Within 'branches' function execute two independent promise requests concurrently

---

package.json
src/views/4_PromptComponent.tsx
src/views/AutocompleteComponent.tsx

Ran into some issue upgrading typescript and electron-builder. This update the other deps.

Update most deps

---

housekeeping/deploy.sh

Reverts vshatskyi/black-screen#983

Revert "Fix deploy"

---

src/views/keyevents/Keybindings.ts

This resolves vshatskyi/black-screen#978

Change keybinding for "Toggle Full Screen" to match macOS default

---

src/utils/PaneTree.ts

Simplified code and improved performance of PaneList next & previous methods.

Improve performance of PaneList next & previous methods

---

README.md

I'm not sure if it's a good time to say this, but seeing as there is now experimental support (see #800) we should potentially update the README.md explaining that it's theoretically possible.

Change README.md explaining unofficial Windows Support

---

README.md

Hint about renaming #1080

---

test/ansi_parser_spec.ts
test/references.d.ts

This is a suggested fix for ANSI Parser test issue #1099

Ansi Parser Test Fix

---

src/views/OutputComponent.tsx
src/views/css/main.ts
test/output_component_spec.tsx

Fix cursor rendering by re-rendering row when cursor column is changed

---

src/views/FooterComponent.tsx
src/views/css/styles.ts
src/views/index.html
test/Pane_spec.tsx

Download New Release link added to the bottom of the terminal when current version is not equal to the one on Github

New release download link

---

src/views/index.html

Just add one line of css to .close-button in index.html

Change close button cursor to pointer in TabHeader

---

package.json
src/Autocompletion.ts
src/EmitterWithUniqueID.ts
src/services/HistoryService.ts
src/shell/History.ts
src/shell/Job.ts
src/shell/Session.ts
src/utils/Common.ts
src/utils/Shell.ts
src/views/PromptComponent.tsx
tsconfig.json

Related issue: https://github.com/railsware/upterm/issues/1128

Extend History

---

src/plugins/autocompletion_providers/Ps.ts

Changes made to the ps autocomplete provider to work with monaco based Suggestion items.

Changes to ps autocomplete for monaco

---

src/plugins/autocompletion_providers/Find.ts
src/plugins/autocompletion_providers/Scp.ts
src/plugins/autocompletion_providers/Tail.ts

Add simple autocompletion for basic commands

Add autocompletion for commands find, scp, tail

---

src/views/menu/Menu.ts

Add new commands:
* `Upterm > Hide (CMD + H)`
* `Upterm > Hide Others (OPTIONS + CMD + H)`
* `Upterm > Unhide`
* `Window > Minimize (CMD + M)`
* `Window > Close`
Solve issue: https://github.com/railsware/upterm/issues/1303

Add menu commands: minimize, close, hide
