railsware/upterm

package.json
'package' command have incorrect `rm` path as for me so I've noticed that overwrite allow to update app without searching and removing output folder
=> Add overwriting to package

src/main/main.js
Now scrollbars are hidden by default and appear only on scrolling also they have dark color what prettier that default OS X
**Before:**
**After:**
**On scrolling:**
Here drop-down list hidden behind the line becouse of strange screenshot system
=> Add overlay-scrollbars

package.json
* Don't use `rm` because it doesn't work on Windows.
* Move the `bower` commands to the `postinstall` hook since it might not be installed yet.
=> Move bower to postinstall.

dts/typings/pty.js/pty.js.d.ts, src/Aliases.ts, src/Invocation.ts, src/references.ts
=> Add d.ts typing for pty.js

src/main/main.js
Hello, I was getting the following exception when running `npm start`
```
Uncaught Exception:
TypeError: Cannot read property 'setMenu' of undefined
at Object.module.exports.setMenu (/home/erick/projects/black-screen/src/main/menu.js:210:23)
at createWindow (/home/erick/projects/black-screen/src/main/main.js:35:7)
at EventEmitter.<anonymous> (/home/erick/projects/black-screen/src/main/main.js:10:15)
at emitOne (events.js:82:20)
at EventEmitter.emit (events.js:169:7)
```
I think the wrong variable is been passed to the `menu.setMenu`
=> Fixing createWindow from main.js

gulpfile.babel.js, package.json
Proposing a solution for #32. 
It seems like the tasks for compiling `typescript`, `react` and `sass` isn't run before `npm run package`, which is what's causing this issue, if you haven't run `npm start` yet.
This is a possible scenario that works.
@luizkowalski @jbaskeen @mzgnr
=> Updates package script to run gulp build before electron-packager

package.json
- Arch *ia64* doesn't exist, it's x64.
- Set an exact version for the module **ptyw.js**.
- Create "productName" & "electronVersion" parameters and use them in the different scripts.
In addition, I think it's time to bump the package version to something like 0.0.3-alpha (this last has not been added to the PR yet).
=> Adjust build scripts

package.json
Spaces ignored and therefore second part of name was loosed after packaging
=> Fix application name

package.json, src/main/Main.ts
- `loadUrl` has become `loadURL`
- `ipc` module has been renamed to `ipcMain`
Full changelog: https://github.com/atom/electron/releases/tag/v0.35.0
=> Updated Electron to 0.35.0 and fixed deprecation warnings

src/views/4_PromptComponent.ts, src/views/AutocompleteComponent.ts
This does three main things:
1) Hovering a suggestion changes `highlightedSuggestionIndex`.
2) A click on a suggestion calls `selectAutocomplete()` (i.e it autocompletes the input with the clicked suggestion)
3) `suggestionComponent` is now styled with `{cursor: "pointer"}` so it actually looks clickable.
Any thoughts ? :-)
=> Add clickable suggestions for AutocompleteComponent

src/views/AutocompleteComponent.ts
While I was hacking away on adding clickable suggestions, I noticed the misspelling in `SuggestionCompoonent`.
Is there any reason why it was named that way ? 
Anyway, this PR renames the React component `SuggestionCompoonent` to `SuggestionComponent`
I've run ag on the codebase to make sure I caught all occurences. Looks like the component is not used outside of this single file.
=> Fix spelling on SuggestionCompoonent

package.json, src/main/Main.ts
Fixes #50 
I tested this locally and it seems to work. 
I've never used TypeScript before, so I hope this is the correct approach. Please let me know if it isn't!
=> Add fixPath() to Main.ts, allows correct $PATH on OSX

src/main/Menu.ts
This replace the deprecated `restart()` method with `reload()`.
From what I've seen, they should both behave the same way.
Fix https://github.com/shockone/black-screen/issues/196
=> Replace deprecated restart() method with reload()

README.md
The relative "issues/58" link pointed within the repo, so that didn't work.
=> Fix TODO link

.gitignore
Modified the project .gitignore to include the Visual Studio Code (vs code) workplace settings folder.
Vs code uses the .vscode directory to store settings such files as tasks.json and launch.json. See vs code documentation:
https://code.visualstudio.com/Docs/customization/userandworkspace
=> Modified .gitignore to include Visual Studio Code workplace settings folder

src/History.ts
This change removes leading, trailing and multiple spaces from commands before they are added to session history.
=> Removed redundant spaces in commands before adding to session history

src/views/1_ApplicationComponent.tsx, src/views/TabComponent.tsx, stylesheets/main.scss
This change adds close buttons to tabs - these are visible when more than one tab is open. A sample of the close buttons is shown in the following screenshot.
The close button changes on focus. See additional sample screenshot below.
=> Tab close buttons

src/views/4_PromptComponent.tsx
Fixed issue (#380) where dragging a file onto terminal window caused file to be opened, getting rid of the terminal.
=> Drag and drop fix

package.json, src/utils/Common.ts, test/utils/common_spec.ts
- Using lstat method (which is not following symlinks) instead of stat.
- Adding mock-fs test dependency to enable unit test
fixes #533
=> Fixing Common.stat method to accept a broken symlink.

src/main/Menu.ts
Added _'Hide Black Screen'_ and _'Hide Others'_ commands to the menu as well as shortcuts for them: 
**Cmd + H** and **Alt + Cmd + H** respectively. (referencing issue: #444 )
=> Added 'Hide Black Screen' and 'Hide Others'  commands #444

package.json
=> Fixes deprecated app-bundle-id

src/views/4_PromptComponent.tsx, src/views/css/definitions.ts, src/views/css/main.ts
Previously, some elements would overlap if you enter multiple lines in the prompt (via pasting). This fixes that, although it introduces some (less bad, IMO) visual glitches in the sticky top prompt.
=> Improve display when pasting multiple lines

src/utils/Common.ts, src/utils/Shell.ts
I noticed the shell() function was memoizing, which seems unnecessary since it's not an expensive operation and is only ever called once anyway. I also removed `baseName`, which seems to be a re-implementation of built in function `basename`.
=> Clean up code for finding user's shell

src/shell/History.ts, src/shell/Session.ts, src/utils/Common.ts, src/utils/Shell.ts
Due to some bugs in black-screen I switch between iTerm2 and black-screen. This change reads the command history from both history files, putting the one that was written to most recently first.
=> Load both ~/.bash_history and ~/.black-screen/history

src/views/css/definitions.ts, src/views/css/main.ts
This fixes #615.
Another option would be to relax the type definition for that field to allow only some ligatures to be disabled.
=> Removed ligatures from prompt

src/utils/Shell.ts
Bash (at least on mac) loads from ~/.profile as well
=> Use ~/.profile file (fixes #618)

src/views/4_PromptComponent.tsx
Fix by allowing the event to continue propagating when job is not in progress.
Fixes #635
=> Fix pasting when prompt already contains text

src/PTY.ts, src/shell/Environment.ts
The removes all `BASH_FUNC_foo%%` env vars at load time, as those cause issues when actually running bash commands. I couldn't find a better place to put this, if you have a suggestion I'd be happy to move it there.
=> Strip bash funcs

src/Autocompletion.ts, src/plugins/autocompletion_providers/Common.ts, src/views/4_PromptComponent.tsx
Show commands run in the past as autocomplete suggestions if their prefix matches what you've already typed.
=> Add commands from history to autocomplete

src/plugins/autocompletion_providers/Cp.ts, src/utils/ManPageParsingUtils.ts, src/utils/ManPages.ts, test/utils/ManPages_spec.ts
After this one I will make a PR that auto-detects the number of spaces in a line that is part of the same paragraph.
=> Add ability to parse man pages with line breaks in a flag description, and cp autocomplete

src/plugins/autocompletion_providers/Grep.ts, src/plugins/autocompletion_utils/Common.ts
I added additional auto-complete options to the grep auto-completion provider. Three types of options were added:
- Standard options with free-text values e.g. --version, --regexp.
- Options with a fixed set of values/ enumerated types e.g. --binary-files, --devices.
- Options who's values are file or directory paths e.g. --file, --exclude-dir.
=> Grep auto complete

src/Enums.ts, src/views/UserEventsHander.ts, src/views/keyevents/Keybindings.ts, src/views/menu/Menu.ts
Allows editing of default keybindings by editing src/views/keyevents/Keybindings.ts
Adds menu support for Windows & Linux by using the 'CmdOrCtrl' accelerator, by default copy is bound to Ctrl+Shift+C for Windows/Linux.
All the keybinding defaults were set from the existing code.
=> Added Keybinding support & Menu support for Linux/Windows

tsconfig.json
Inline sourcemaps output the sourcemap as a special comment at the bottom of the compiled js files. This allows debugging in TypeScript code instead of compiled JavaScript. 
In a production web environment this flag should not be used because it makes each *.js file larger. But in an electron environment it appears the size of *.js files doesn't really matter because files are loaded directly from the local device. 
https://discuss.atom.io/t/minification-of-js-css-for-atom-shell/15528
I believe this is a cleaner way than outputting *.map files and because we are using electron the file size increase has no effect on performance (micro optimization).
=> Add inline sourcemaps to tsconfig.json

src/utils/Git.ts
Fixes #741, which was caused by `Unknown git status code: "M "` interfering with the autocomplete
=> Fix git add autocomplete 

src/plugins/autocompletion_providers/Ps.ts, src/utils/Process.ts
This PR provides auto-complete functionality for the "ps" command and some of the the options available.
The long-flag options provide suggested values based on the values available. These values can be chained together separated by commas. The example in the screenshot attached is for the "--pid" (process id) option and shows a number of values entered separated by commas. 
I would like to cache calls for long-flag option to save multiple calls to fetch available options. In the "src/utils/Process.ts" file I attempted to do this by using memoize to cache the results of the processes function (see annotation inline). Unfortunately the result is cached for the entire terminal session - I need to cache this for each terminal command instance (if that makes sense).
Please let me know if you …
=> Added ps auto-complete functionality

src/PTY.ts
I have this in my `~/.profile`:
```bash
function s() {
if [[ -t 0 ]]
then
#not piping
subl "$@" &
else
#piping
contents=$(cat)
subl "$@" <<< "$contents" &
fi
}
export -f s
```
It doesn't work unless I make the following change. I'm not exactly sure why, but also the "interactive" flag does seem to be appropriate for `black-screen`, since the launched programs are, in fact, interactive.
=> Force shells to be interactive

src/Enums.ts, src/views/1_ApplicationComponent.tsx, src/views/UserEventsHander.ts, src/views/keyevents/Keybindings.ts, src/views/menu/Menu.ts
Hi, you have an awesome app, just noticed it couple of days ago and no I'm hooked!
One thing I was missing was the tab navigation (prev/next) functionality, I took the liberty to implement it, I tried to follow the code style and tested it manually on MacOS 10.11.6. You did a great work and the source code is very readable, so it took couple of hours to implement the feature, the development environment worked without glitches. I would recommend to switch to stateless components design model though, as it seem like the app has high view-logic dependencies.
If your looking for collaborators, I'm up for the task, I have experience with nodejs, electron, react and typescript.
P.S
I also bound the meta key to the indexed tab switch (keeping the old ctrl bind in tact), the tab header place the …
=> Tab navigation

src/plugins/Ls.tsx, src/shell/Job.ts
Now if the interceptor fails, it will fall back to the original command that was supposed to be intercepted.
=> Improve handling of failing interceptor plugins

src/plugins/autocompletion_utils/Common.ts, src/utils/Git.ts
Convert git status type to be a union of string literals instead of an enum. This will be very helpful for a git plugin I'm working on.
=> Convert Git StatusCode enum to string literal type

src/shell/Job.ts
I'm not 100% sure about this fix. It causes `sleep 10` then `alt+d` to display the same thing as in `iTerm` when in "Alt key = ESC+" mode. I was never able to make vim work the way @Alok described in either `black-screen` or `iTerm`. @shockone would you be able to review this one? I'm not very familiar with the ANSI/escape codes stuff.
=> Fix alt key

src/views/2_SessionComponent.tsx
The prevents the window from needing to be scrolled to show the input bar after cancelling a job
=> Snap to bottom when near bottom and job is finished

src/views/keyevents/Keybindings.ts
On macOS, `Edit>Find` has the same keybinding as `View>Toogle Full Screen`, namely `CMD+F`.
This pull request reassigns full screen to `CMD+Shift+F` on mac. As a side-effect, the accelerator can be unified to `CmdOrCtrl+Shift+F` which is equal to the previous mapping on all other operating systems.
=> Fix conflicting keybindings for "fullscreen" and "find" on macOS (CMD+F)

src/views/4_PromptComponent.tsx, src/views/UserEventsHander.ts
A common workflow for me is:
1) Run a command
2) Scroll up to see it's output
3) Switch to editor to edit something
4) Switch back, run press up to run same command
5) Repeat
When I do this, I want the prompt to scroll into view, so I
can see what I am actually about to execute. This PR makes that happen
=> Scroll prompt into view when cycling history

src/Autocompletion.ts, src/views/4_PromptComponent.tsx, test/autocompletion_spec.ts
`getSuggestions` doesn't need the whole job, and giving it the whole job causes it to be hard to test. This changes it to only accept the things it needs, and also adds a test for it.
=> Change autocompletion API to make it more testable, and add a test for it

src/Autocompletion.ts, src/Interfaces.ts, src/plugins/autocompletion_utils/Common.ts, src/shell/Parser.ts, src/views/4_PromptComponent.tsx, test/autocompletion_spec.ts
Fixes #933 by treating special casing completion for `CommandWord` if there is a space after the command. This was formerly impossible, but became possible after #903.
=> Fix issue causing autocomplete arguments after a space to not work.

src/plugins/autocompletion_providers/Git.ts, src/plugins/autocompletion_providers/NPM.ts, src/plugins/autocompletion_providers/Rails.ts, src/plugins/autocompletion_providers/Vagrant.ts, src/plugins/autocompletion_utils/Common.ts
Create a reusable abstraction for commands with subcommands, and have the `Git`, `NPM`, and `Vagrant` autocompletion providers use it.
=> Unify subcommand autocomplete

src/shell/Job.ts, src/shell/Scanner.ts, test/shell/scanner_spec.ts
Fixes #938
I realized that there are two conflicting issues here: autocomplete cares about spaces, and wants them to not be removed, and plugins don't care about spaces, and want them to be removed. All my approaches so far had been to deal with whitespace at the parser level and then try to make autocomplete happy, bit I realized it's much simpler to leave the parser as-is, and filter out `Invalid` tokens before handing them to the plugins.
This PR reverts my changes to "eat" whitespace at the end of tokens, which fixes autocomplete, and filters `Invalid` tokens out of commands before handing to plugins.
=> Finally fix autocomplete after space and also plugins without words

src/EmitterWithUniqueID.ts, src/shell/CommandExecutor.ts, src/shell/Job.ts, src/views/UserEventsHander.ts
There is a brief window in between when the `Job`'s `status` is set to `InProgress`, and when it's `PTY` is created. If the user types a key in that window, `job.write` will be called, which expects the `PTY` to exist, but it doesn't, causing a crash. This PR fixes that issue.
In general, I think we should move away from using `job.status`, and instead, have methods that check exactly what the caller wants to know about the job. `job.status` is essentially supposed to be a reflection of the `job`'s internal state, but because of all the `async` stuff in there, it's just not very good at doing that.
=> Fix a crash where PTY isn't launched

src/shell/Scanner.ts, test/shell/scanner_spec.ts
Fixes https://github.com/vshatskyi/black-screen/issues/957
The problem is that Scanner splits tokens made up of several string literals, like key="value". The solution is to squash literals into composite literals if there are no spaces between them.
I moved StringLiteral class because it needs to be above Word class, because Word now extends StringLiteral.
=> Fix scanner splitting literals with quotes (#957)

src/PTY.ts
On linux autocompletion doesn't work and `npm test` fail on autocompletion because of
`/bin/sh: 1: printf: %q: invalid directive`
Setting child_process default shell to /bin/bash fix autocompletion and tests.
I don't know if it causes any issues on osx, but on linux it works like a charm.
=> fix autocomplete on linux

package.json
I renamed 'electron-prebuilt' to 'electron' in package.json file. The 'electron-prebuilt' package name has been deprecated and was causing errors when running on my Ubuntu development machine (running Ubuntu 16.04.2 LTS with node.js 7.6.0).
=> Renamed 'electron-prebuilt' to 'electron'

src/plugins/autocompletion_providers/Ls.ts, src/plugins/autocompletion_utils/Common.ts
Added function 'combineShortFlags' to support entry of short flag combinations for auto-complete providers.
=> Support combinations of short flags for auto-completion providers

src/utils/PaneTree.ts
Update implements wrap around when advancing next & previous panes.
Code to address issue #977.
=> Allow wrap around when advancing next & previous pane

docs/vscodedebugging.md
Made some updates to the vscode debugging instructions to:
- Use the node "inspector" debug protocol.
- Removed erroneous instructions for debugging compiled javascript file.
- Changed vscode tested to 1.12.1.
=> Updated vscode debugging instructions

README.md
Added a new install entry to README for Arch Linux users since Black Screen is available for automated install via `yaourt` (AUR).
=> Updated README to include an Arch Linux install guide (yaourt).

src/views/keyevents/Keybindings.ts
Search is focused and we need to give the focus back to prompt.
=> Fix #1081. Refocus prompt when escape from search component.

src/main/Main.ts, src/views/ApplicationComponent.tsx, src/views/NavButtonsComponent.tsx, src/views/index.html
Hidden the original title-bar and created a new one, with custom buttons.
Not tested in a mac.
=> Custom inset tittle bar

src/views/index.html
Making the active tab a bit more apparent with borders and background color.
Before:
After:
Fixes item 3 in https://github.com/railsware/upterm/issues/1192.
=> Tab Headers Legibility Improvements
